### ISSUE TITLE
Globals items

### ISSUE THREAD

**Issue by abon999** [ovk/brackets-simple-todo#12]
Hi, is there any way to set items to global context, not per-project lists ?

Nice plugin btw.

**Comment by ovk** [comment]
Hi @abon999. Currently all items which are stored in file are per-project. I'm planning to make to-do file path configurable with some predefined variable for current project folder, for example: `{CUR_PROJECT}\todo.txt`. Thus, it will be possible to make this path nod dependent on the project and have global to-do list: `C:\some_folder\todo.txt`. 

Meanwhile, you can use Trello storage to store your to-do list, as it is always global.

**Comment by abon999** [comment]
Thx for the reply.
I'll wait for an update caus I don't want to store profesionnal todos into cloud.
