### ISSUE TITLE
Linking file.

### ISSUE THREAD

**Issue by Athax** [ovk/brackets-simple-todo#14]
It could be awesome to be able to link a file to a to-do list, like when you press a to-do list or category, it would open up the chosen file.

**Comment by ovk** [comment]
I didn't quite understand what do you mean. Are you talking about attaching images or text files to a to-do item?

**Comment by Athax** [comment]
Im talking about opening up a file like a php or html file, in the editor screen.

**Comment by ovk** [comment]
Well, it's not easy to implement this at the moment (since a to-do item doesn't have any properties or tags where such information clould be stored), but maybe I'll add this in the future.

**Comment by Athax** [comment]
Would make this plugin, a lot cooler.

**Comment by ovk** [comment]
For now you can use [Brackets Todo](https://github.com/mikaeljorhult/brackets-todo) for these purposes.

**Comment by Athax** [comment]
Thanks, but i would rather wait. ;)
